### ISSUE TITLE
El modulo se cae cuando es intenta procesar un producto

### ISSUE THREAD

**Issue by Pablo-Centry** [CentryCL/centry_ps_esclavo#10]
En esta línea faltó agregar el ; al final:
https://github.com/CentryCL/centry_ps_esclavo/blob/c06c7b9663b1d7a5884e0faeef1122a284a4ba46/sdk/CentrySDK.php#L114

En esta línea faltó agregar los paréntesis en la validación de if:
https://github.com/CentryCL/centry_ps_esclavo/blob/c06c7b9663b1d7a5884e0faeef1122a284a4ba46/sdk/CentrySDK.php#L115

**Comment by eliaslama** [comment]
https://github.com/CentryCL/centry_ps_esclavo/commit/4ce9cb72f89e9d700a48769ed7a796b36ed07e7c
