### ISSUE TITLE
Error en la llamada de la función response

### ISSUE THREAD

**Issue by Pablo-Centry** [CentryCL/centry_ps_esclavo#11]
En esta línea de código el valor correcto debería ser "return $this->response($response, $err, $info);" ya que se está llamando a un método de la misma clase.

https://github.com/CentryCL/centry_ps_esclavo/blob/c06c7b9663b1d7a5884e0faeef1122a284a4ba46/sdk/CentrySDK.php#L100

**Comment by eliaslama** [comment]
https://github.com/CentryCL/centry_ps_esclavo/commit/4ce9cb72f89e9d700a48769ed7a796b36ed07e7c
