### ISSUE TITLE
Errores en if

### ISSUE THREAD

**Issue by Pablo-Centry** [CentryCL/centry_ps_esclavo#12]
https://github.com/CentryCL/centry_ps_esclavo/blob/4ce9cb72f89e9d700a48769ed7a796b36ed07e7c/classes/translators/Products.php#L326
En esta linea de código se está indicando el $custom como un booleano, sin embargo, cuando se utiliza la función "featureValue" en otras partes del código se está enviando un número, para mi entender lo correcto debería ser así:

if ($feature_value && ($prod_id || $custom == 0)) {

https://github.com/CentryCL/centry_ps_esclavo/blob/4ce9cb72f89e9d700a48769ed7a796b36ed07e7c/classes/translators/Products.php#L332
En esta linea considerar agregar el (bool) en $custom, como mencioné no se entrega un valor booleano, se entrega un valor numérico. Debería quedar así:

$feature_value->custom = (bool) $custom;

**Comment by eliaslama** [comment]
No es necesario. https://www.php.net/manual/es/language.types.boolean.php#language.types.boolean.casting
