### ISSUE TITLE
Error variable no definida

### ISSUE THREAD

**Issue by portrab** [CentryCL/centry_ps_esclavo#13]
https://github.com/CentryCL/centry_ps_esclavo/blob/4ce9cb72f89e9d700a48769ed7a796b36ed07e7c/controllers/front/centryproductsave.php#L60

Se debe modificar la variable "$resp->_id" por "$centry_id"

**Comment by eliaslama** [comment]
Corregido el problema. Gracias por el reporte.
https://github.com/CentryCL/centry_ps_esclavo/commit/2b69dc545cde9931a1dfc2636a681fdb2cf5e912
