### ISSUE TITLE
homologación errónea del estado "Recibido" de Centry

### ISSUE THREAD

**Issue by Pablo-Centry** [CentryCL/centry_ps_esclavo#9]
En estas líneas se está indicando de forma errónea la homologación con el estado "Recibido" de Centry:

https://github.com/CentryCL/centry_ps_esclavo/blob/c06c7b9663b1d7a5884e0faeef1122a284a4ba46/centry_ps_esclavo.php#L568
https://github.com/CentryCL/centry_ps_esclavo/blob/c06c7b9663b1d7a5884e0faeef1122a284a4ba46/centry_ps_esclavo.php#L569

El valor correcto de homologación debería ser "received" y actualmente está como "recieved".

**Comment by eliaslama** [comment]
Gracias por el reporte, se ha resuelto en el commit https://github.com/CentryCL/centry_ps_esclavo/commit/4ce9cb72f89e9d700a48769ed7a796b36ed07e7c
